# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
#cache: packages
sudo: false
bioc_required: false
bioc_use_devel: true
warnings_are_errors: false
notifications:
    email: false
    slack: 
        on_success: change
        on_failure: change
        rooms:
            - eb-group-aau:FXLq5xhPHEEmmNLMHlQrpiCd#ampvis_development
r_packages:
  - covr
after_success:
  - Rscript -e 'library(covr); codecov()'
