# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r: bioc-devel
warnings_are_errors: false
notifications:
    email: false
    slack: eb-group-aau:FXLq5xhPHEEmmNLMHlQrpiCd
        on_succes: change
        on_failure: always